version: '3.4'
services:

  postgres:
    container_name: droplet_postgres
    image: bitnami/postgresql:13
    ports:
      - "5432:5432"
    networks:
      - droplet_network
    volumes:
      - ./postgres/data:/bitnami/postgresql
    env_file:
      - ./postgres/postgres.env


networks:
  droplet_network:
    
