version: '3.4'
services:

  postgres:
    container_name: droplet_postgres
    image: bitnami/postgresql:13
    ports:
      - "5432:5432"
    networks:
      - droplet_network
    volumes:
      - ./postgres/data:/bitnami/postgresql
    env_file:
      - ./postgres/postgres.env

  zookeeper:
    container_name: droplet_zookeeper
    image: bitnami/zookeeper:3.7.0
    ports:
      - "2181:2181"
    networks:
      - droplet_network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: droplet_kafka
    image: bitnami/kafka:3.1.0
    ports:
      - "9092:9092"
    networks:
      - droplet_network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


networks:
  droplet_network:
    
